service: lalu-portfolio-backend
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  timeout: 30
  environment:
    GOOGLE_API_KEY: ${env:GOOGLE_API_KEY}
    PINECONE_API_KEY: ${env:PINECONE_API_KEY}
    PINECONE_ENVIRONMENT: ${env:PINECONE_ENVIRONMENT}
    PINECONE_INDEX: ${env:PINECONE_INDEX}
    API_SECRET_KEY: ${env:API_SECRET_KEY}
    SYSTEM_PROMPT: ${env:SYSTEM_PROMPT}
    VOICERSS_API_KEY: ${env:VOICERSS_API_KEY}

functions:
  api:
    handler: build/lambda.handler
    events:
      - httpApi:
          path: "*"
          method: "*"
          cors: true # Add this line
          throttle:
            rate: 5 # Maximum 5 requests per second
            burst: 10 # Maximum 10 concurrent requests

plugins:
  - serverless-offline

package:
  include:
    - build/**
    - frontend_data/**
